---
- name: Upgrade RouterOS on Mikrotik devices
  hosts: mikrotik_routers
  gather_facts: no
  tasks:
    - name: Reset configuration
      community.routeros.command:
        commands:
          - :execute {/system reset-configuration keep-users=yes;}
      register: command_result
      failed_when: "'Received SSH_MSG_DISCONNECT' not in command_result.msg"


